config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to: 'lists#index'
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end

  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates_uniqueness_of :movie_id, scope: :list_id
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true
  validates :name, uniqueness: true

end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, uniqueness: true
  validates :title, :overview, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list_id = @list.id
    if @bookmark.save
      flash[:notice] = "Bookmark was successfully created."
      redirect_to list_path(@list)
    else
      flash[:alert] = "There was an error creating the bookmark."
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    flash[:notice] = "Bookmark was successfully deleted."
    redirect_to bookmark_path(@bookmark)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
    @movies = Movie.all
  end

  def show
    @list = List.find(params[:id])
    @bookmarks = @list.bookmarks
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(lists_params)
    if @list.save
      flash[:notice] = "List was successfully created."
      redirect_to list_path(@list)
    else
      flash[:alert] = "There was an error creating the list."
      render :new
    end
  end

  private
  def lists_params
    params.require(:list).permit(:name, :image, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/_navbar.html.erb
<ul>
  <li>
    <a href="<%= lists_path %>" class="logo">
      <%= image_tag '66356c25ce98cb12993249e21742b129.png', alt: 'Logo', style: 'width: 30px; height: auto;' %>
    </a>
  </li>
  <li style="float:right"><a class="active" href="#about"><%= link_to "Create List", new_list_path %></a></li>
</ul>

app/views/bookmarks/new.html.erb
<%= render 'navbar' %>

<div class="page-name">
  <h3>Bookmark a Movie</h3>
</div>

<div class="form">
  <div class="form-size">
    <%= simple_form_for [@list, @bookmark] do |t| %>
      <div class="text-area">
        <div class="text"><%= t.input :comment %></div>
        <div class="text"><%= t.association :movie %></div>
      </div>
      <%= t.submit "Add", class: "btn btn-dark-blue" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div class="flash-container">
    <% flash.each do |key, message| %>
      <div class="alert alert-<%= key %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/lists/_navbar.html.erb
<ul>
  <li>
    <a href="<%= lists_path %>" class="logo">
      <%= image_tag '66356c25ce98cb12993249e21742b129.png', alt: 'Logo', style: 'width: 30px; height: auto;' %>
    </a>
  </li>
  <li style="float:right"><a class="active" href="#about"><%= link_to "Create List", new_list_path %></a></li>
</ul>

app/views/lists/index.html.erb
<%= render 'navbar' %>

<div class="page-name">
  <h3>My Watch List</h3>
</div>


<div class="cards">
  <% @lists.each do |list| %>
    <% if list.photo.attached? %>
      <a href="<%= list_path(list) %>" class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path list.photo.key%>); text-decoration: none;">
        <%= list.name %>
      </a>
    <% else %>
      <a href="<%= list_path(list) %>" class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg); text-decoration: none;">
        <%= list.name %>
      </a>
    <% end %>
  <% end %>
</div>

app/views/lists/new.html.erb
<%= render 'navbar' %>

<div class="page-name">
  <h3>Add List</h3>
</div>

<div class="form">
  <div class="form-size">
    <%= simple_form_for(@list) do |t| %>
      <div class="text-area">
        <div class="text"><%= t.input :name %></div>
        <div class="text"><%= t.input :photo, as: :file %></div>
        <%= t.submit "Add", class: "btn btn-dark-blue" %>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/show.html.erb
<%= render 'navbar' %>
  <%# How chaining methods works %>
<div class="page-name">
  <h3><%= @list.name %> Page <%= link_to "Add bookmark", new_list_bookmark_path(@list), class: "btn btn-dark-blue"%></h3>
</div>

<div class="container">
  <% if @bookmarks.empty? %>
    <div class="d-flex justify-content-center">
      <%= image_tag 'empty-folder_2456758.png', alt: 'Empty folder picture' %>
    </div>
  <% else %>
    <% @bookmarks.each do |bookmark| %>
      <div class="card-product">
        <div class="flex-icon">
        </div>
        <img src="<%= bookmark.movie.poster_url %>" />
        <div class="card-product-infos">
          <h2><%= bookmark.movie.title %></h2>
          <p>Rating: <strong><%= bookmark.movie.rating %></strong></p>
          <p>" <%= bookmark.comment %> "</p>
        </div>
          <div class="trash-icon">
              <%= link_to '🗑️', bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'no-underline' %>
          </div>
      </div>
    <% end %>
  <% end %>
</div>